env:
  browser: true
  jquery: true
extends: 'eslint:recommended'
globals:
  App: true
  Battletype: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console: "off"
  quotes:
    - error
    - double
  semi:
    - error
    - always
